### ISSUE TITLE
Add CfgMgmtCamp to FOSDEM Fringe page

### ISSUE THREAD

**Issue by purpleidea** [cfgmgmtcamp/cfgmgmtcamp.github.io#322]
Here's the link:

https://fosdem.org/2018/fringe/

It asks that an "organiser of an event" add it, so since I'm not officially an organizer, I suppose someone else might want to do this. Happy to do it if someone gives me an official ACK.

Cheers

**Comment by toshywoshy** [comment]
Thanks for the reminder, I send an application.

**Comment by nathenharvey** [comment]
<img width="798" alt="fosdem_2018_-_fringe" src="https://user-images.githubusercontent.com/16093/33520593-21cb134e-d78c-11e7-96b6-90e76f757c80.png">

**Comment by nathenharvey** [comment]
hmmm...I'd like to close this since it's done but it doesn't look like I have permission to do so.
