### ISSUE TITLE
issue with dates on food page

### ISSUE THREAD

**Issue by dpnl87** [cfgmgmtcamp/cfgmgmtcamp.github.io#353]
There seems to be an issue with the days on the food page:

<img width="437" alt="screen shot 2018-01-29 at 22 04 45" src="https://user-images.githubusercontent.com/85584/35534337-7a286bfe-0540-11e8-8230-4ad7721b90ff.png">

**Comment by toshywoshy** [comment]
Did you forget how to send PR?
Anyway corrected, thank for noticing.
